### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by franck-paul** [Korben00/AuthyExtractor#1]
Je viens de tester le clone, suivi du pip install … indiqué dans la doc, mais ça plante copieusement, une première fois parce qu'il manquait  `pip install tk-tools` puis ensuite, j'ai du cloner l'appli "Authy" en "Authy Desktop", puis ensuite :

```
python authy-export.py
Launching Authy
Exception in Tkinter callback
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/opt/homebrew/lib/python3.11/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/opt/homebrew/lib/python3.11/site-packages/urllib3/connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 975, in send
    self.connect()
  File "/opt/homebrew/lib/python3.11/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
           ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x1046d1c10>: Failed to establish a new connection: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=5858): Max retries exceeded with url: /json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1046d1c10>: Failed to establish a new connection: [Errno 61] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/tkinter/__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "~/Documents/EGO/Geekeries/Projets/authy-export/authy-export.py", line 65, in on_button_click
    chromex = PyChromeDevTools.ChromeInterface(host='localhost', port=5858)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/PyChromeDevTools/__init__.py", line 49, in __init__
    self.connect(tab=tab)
  File "/opt/homebrew/lib/python3.11/site-packages/PyChromeDevTools/__init__.py", line 57, in connect
    self.get_tabs()
  File "/opt/homebrew/lib/python3.11/site-packages/PyChromeDevTools/__init__.py", line 52, in get_tabs
    response = requests.get(f'http://{self.host}:{self.port}/json')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=5858): Max retries exceeded with url: /json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1046d1c10>: Failed to establish a new connection: [Errno 61] Connection refused'))
[1]    18688 segmentation fault  python authy-export.py
```

Je merdoie où ?

**Comment by fenneclabs** [comment]
Peut être que ton Authy est déjà lancé? Il vaut que cet outil puisse le relancer en mode debug.

**Comment by franck-paul** [comment]
Nope, même résultat.

**Comment by franck-paul** [comment]
Précision éventuelle à mettre dans les instructions : ça ne fonctionne qu'avec la version téléchargeable sur le site Authy (Twilio) mais pas avec l'appli installée depuis l'AppStore Apple.

**Comment by fenneclabs** [comment]
Dans un terminal essaye:
`open -a 'Authy' --args --remote-debugging-port=5858`

Ensuite essaye de browser http://localhost:5858/

Si tu as une page "Inspectable WebContents", tu peux ensuite essayer de lancer l'export, sans fermer ton Authy.

**Comment by fenneclabs** [comment]
Tu peux aussi essayer de changer le fichier functions/launch_authy.py line 15, remplace 'Authy Desktop' par 'Authy'

**Comment by franck-paul** [comment]
> Dans un terminal essaye: `open -a 'Authy' --args --remote-debugging-port=5858`
> 
> Ensuite essaye de browser http://localhost:5858/
> 
> Si tu as une page "Inspectable WebContents", tu peux ensuite essayer de lancer l'export, sans fermer ton Authy.

J'avais fait le test, mais ça ne passait pas avec l'appli de l'AppStore — je pense que le mode debug n'est pas actif pour celle-ci, pas moyen d'atteindre la page web dans chrome —, uniquement avec celle (Authy Desktop) téléchargée depuis le site.
